services:
  glim-container:
    image: uvslam:glim
    runtime: nvidia
    environment:
      - DISPLAY=:0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DISTRO=humble
      - ROS_WORKSPACE=/root/ros2_ws
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros2_ws:/host_ros2_ws
      - ./data:/data
    entrypoint: ["/entrypoint.sh"]
    command: ["tail", "-f", "/dev/null"]
    networks:
      - ros-network  # Connects to this network

networks:  # ⚠️ Define the network here (uncommented and properly indented)
  ros-network:
    driver: bridge